print("    *****************************    ")
print("    *****************************    ")
print("   *              *              *   ") 
print("  *               *               *  ")
print(" *                *                * ")
print(" *                *                * ")
print("*                 *                 *")
print("*                 *                 *")
print("* PPPP   EEEEE    A     CCC   EEEEE *")
print("* P   P  E       A A   C   C  E     *")
print("* P   P  E      A   A  C      E     *")
print("* PPPP   EEEEE  AAAAA  C      EEEEE *")
print("* P      E      A * A  C      E     *")
print("* P      E      A * A  C   C  E     *")
print("* P      EEEEE  A * A   CCC   EEEEE *")
print("*          *      *      *          *")
print("*         *       *       *         *")
print("*        *        *        *        *")
print(" *      *         *         *      * ")
print(" *     *          *          *     * ")
print("  *   *           *           *   *  ")
print("   * *            *            * *   ") 
print("    *****************************    ")
print("    *****************************    ")
